"""
HouseAI Map Knowledge Base
--------------------------

Bu dosya ilk sayfadaki HouseAI chatbot için bilgi bankasıdır.
Amaç JS içinde if/else ile çalışan basit bir chatbot yerine Python tarafında
genişletilebilir, emlak alanına özel ve bağlam hatırlayan bir sistem kurmaktır.

Bu dosya doğrudan endpoint çalıştırmaz; houseai_map_chatbot_service.py tarafından kullanılır.
"""

from __future__ import annotations


# =========================================================
# 1) NİYET ANAHTAR KELİMELERİ
# =========================================================

INTENT_KEYWORDS = {
    "add_listing": [
        "ev ilanimi girmek",
        "ev ilanı girmek",
        "ev ilani girmek",
        "ev ilanı gireceğim",
        "ev ilani girecegim",
        "ev ilanı girecem",
        "ev ilani girecem",
        "ev ilan girecem",
        "ilan girmek",
        "ilan gireceğim",
        "ilan girecegim",
        "ilan girecem",
        "ilan eklemek",
        "evimi eklemek",
        "ev eklemek",
        "evimi satacağım",
        "evimi satacagim",
        "evimi satmak istiyorum",
        "satmak istiyorum",
        "konum seçmek",
        "konum secmek",
        "evimin konumu",
        "haritadan seçmek",
        "haritadan secmek",
    ],
    "market_price": [
        "ortalama",
        "fiyat",
        "ne kadar",
        "kaç tl",
        "kac tl",
        "kaça",
        "kaca",
        "piyasa",
        "değer",
        "deger",
        "eder",
        "gidiyor",
        "kaç para",
        "kac para",
        "m2 fiyat",
        "metrekare fiyat",
        "metre kare fiyat",
        "tl",
    ],
    "show_listings": [
        "ilanlari göster",
        "ilanları göster",
        "ilanları getir",
        "ilanlari getir",
        "haritada göster",
        "haritada goster",
        "listele",
        "hepsini göster",
        "hepsini goster",
        "bu mahalledeki ilanlar",
        "seçili mahalledeki ilanlar",
        "secili mahalledeki ilanlar",
    ],
    "cheapest": [
        "en ucuz",
        "ucuzlari",
        "ucuzları",
        "düşük fiyat",
        "dusuk fiyat",
        "uygun fiyat",
        "fiyatı düşük",
        "fiyati dusuk",
    ],
    "expensive": [
        "en pahalı",
        "en pahali",
        "pahalıları",
        "pahalilari",
        "yüksek fiyat",
        "yuksek fiyat",
    ],
    "opportunity": [
        "fırsat",
        "firsat",
        "avantajlı",
        "avantajli",
        "piyasanın altında",
        "piyasanin altinda",
        "ucuz kalmış",
        "ucuz kalmis",
    ],
    "compare_area": [
        "karşılaştır",
        "karsilastir",
        "mi daha iyi",
        "mi daha pahalı",
        "mi daha pahali",
        "hangi mahalle",
        "kıyasla",
        "kiyasla",
        "farkı ne",
        "farki ne",
    ],
    "where_am_i": [
        "neredeyim",
        "hangi mahalle",
        "seçili konum",
        "secili konum",
        "seçtiğim yer",
        "sectigim yer",
        "burasi neresi",
        "burası neresi",
    ],
    "help": [
        "yardım",
        "yardim",
        "ne yapabilirsin",
        "komutlar",
        "neler yaparsın",
        "neler yaparsin",
        "nasıl kullanılır",
        "nasil kullanilir",
    ],
    "reset": [
        "sıfırla",
        "sifirla",
        "baştan",
        "bastan",
        "yeniden başla",
        "yeniden basla",
        "konumu sil",
        "temizle",
    ],
}


# =========================================================
# 2) KONUŞMA ADIMLARI
# =========================================================

CONVERSATION_STEPS = {
    "ASK_DISTRICT": "ask_district",
    "ASK_NEIGHBORHOOD": "ask_neighborhood",
    "AREA_CONTEXT": "area_context",
    "READY": "ready",
}


# =========================================================
# 3) CEVAP ŞABLONLARI
# =========================================================

WELCOME_MESSAGE = (
    "Merhaba 👋 Ben HouseAI. Sana emlak analizi için yardımcı olabilirim.<br><br>"
    "Şunları deneyebilirsin:<br>"
    "• “Kağıthane Hamidiye Mahallesi 3+1 ortalama ne kadar?”<br>"
    "• “Ev ilanımı girmek istiyorum”<br>"
    "• Bir konum seçtikten sonra “ortalama 2+1 ne kadar?” yazabilirsin."
)

HELP_MESSAGE = (
    "<strong>HouseAI neler yapabilir?</strong><br><br>"
    "• Konuşma içinde ilçe ve mahalle hatırlar<br>"
    "• “ortalama 2+1 ne kadar?” gibi eksik konumlu soruları anlayabilir<br>"
    "• Seçili mahalledeki ilanları filtreler<br>"
    "• Ortalama fiyat, medyan fiyat ve m² fiyatı hesaplar<br>"
    "• En ucuz / en pahalı / fırsat ilanları listeleyebilir<br>"
    "• Haritayı ilgili mahalleye götürebilir<br>"
    "• Ev ilanı girmek isteyen kullanıcıya konum seçtirir<br><br>"
    "Örnek: <strong>Talatpaşa 2+1 ortalama ne kadar?</strong>"
)

NO_CONTEXT_MESSAGE = (
    "Henüz hangi bölgeyi sorduğunu anlayamadım.<br><br>"
    "Örnek olarak şöyle yazabilirsin:<br>"
    "• Kağıthane Talatpaşa Mahallesi 2+1 ortalama ne kadar?<br>"
    "• Ev ilanımı girmek istiyorum"
)

ASK_DISTRICT_MESSAGE = (
    "Tabii, ev ilanını girmek için yardımcı olayım. Önce ilçeyi yazar mısın?<br>"
    "Örnek: <strong>Kağıthane</strong>"
)

ASK_NEIGHBORHOOD_TEMPLATE = (
    "Tamam, ilçe: <strong>{district}</strong>.<br>"
    "Şimdi mahallenin adını yazar mısın?<br>"
    "Örnek: <strong>Hamidiye Mahallesi</strong>"
)

AREA_SELECTED_TEMPLATE = (
    "Süper. Haritayı <strong>{district} / {neighborhood}</strong> bölgesine götürüyorum.<br>"
    "Haritada evinin tam konumuna tıkla."
)

AREA_CONTEXT_SET_TEMPLATE = (
    "Konum bağlamını <strong>{district} / {neighborhood}</strong> olarak kaydettim.<br>"
    "Artık sadece “ortalama 2+1 ne kadar?” gibi sorabilirsin."
)

NO_LISTING_TEMPLATE = (
    "<strong>{district} / {neighborhood}</strong> için uygun ilan bulamadım.<br><br>"
    "Seçili mahalleyi korudum; tüm ilçeye genişletmedim."
)

NO_LISTING_DISTRICT_TEMPLATE = (
    "<strong>{district}</strong> içinde bu kriterlere uygun ilan bulamadım."
)

MARKET_SUMMARY_TEMPLATE = (
    "<strong>{area_text}{room_text}</strong> ilanları için yaklaşık piyasa özeti:<br><br>"
    "Ortalama fiyat: <strong>{average_price}</strong><br>"
    "Medyan fiyat: <strong>{median_price}</strong><br>"
    "Ortalama m² fiyatı: <strong>{average_m2_price}</strong><br>"
    "İlan sayısı: <strong>{count}</strong><br>"
    "Fiyat aralığı: <strong>{min_price} - {max_price}</strong><br><br>"
    "{comment}"
)

CHEAPEST_TEMPLATE = (
    "<strong>{area_text}</strong> bölgesinde en uygun fiyatlı ilanları listeledim.<br><br>"
    "Bu liste toplam fiyata göre en düşükten yükseğe sıralandı."
)

EXPENSIVE_TEMPLATE = (
    "<strong>{area_text}</strong> bölgesindeki en yüksek fiyatlı ilanları listeledim.<br><br>"
    "Bu liste toplam fiyata göre yüksekten düşüğe sıralandı."
)

OPPORTUNITY_TEMPLATE = (
    "<strong>{area_text}</strong> bölgesinde piyasa ortalamasına göre daha avantajlı görünen ilanları listeledim.<br><br>"
    "Not: Fırsat etiketi sadece mevcut veri ve m² fiyatı karşılaştırmasına göre hesaplanır."
)

RESET_MESSAGE = (
    "Tamam, HouseAI konuşma bağlamını sıfırladım.<br>"
    "Yeni bir bölge sorabilir veya “ev ilanımı girmek istiyorum” diyebilirsin."
)


# =========================================================
# 4) KISA YORUM ŞABLONLARI
# =========================================================

PRICE_COMMENTS = [
    "Bu sonuçlar mevcut listings.json verisine göre hesaplandı.",
    "Benzer ilan sayısı arttıkça analiz güvenilirliği yükselir.",
    "m² fiyatı toplam fiyattan daha sağlıklı karşılaştırma sağlar.",
    "Medyan fiyat uç değerlerden daha az etkilenir.",
    "Ortalama fiyat bölgedeki genel fiyat seviyesini gösterir.",
]

CONFIDENCE_COMMENTS = {
    "Yüksek": "Bu analizde benzer ilan sayısı güçlü olduğu için güven seviyesi yüksek.",
    "Orta-Yüksek": "Benzer ilan sayısı yeterli görünüyor; analiz güveni orta-yüksek.",
    "Orta": "Veri kullanılabilir ama daha fazla benzer ilan olsa analiz daha güçlü olurdu.",
    "Düşük-Orta": "Analiz ilçe geneline genişlediği için güven seviyesi sınırlı.",
    "Düşük": "Veri az olduğu için bu sonuç daha dikkatli yorumlanmalı.",
}


# =========================================================
# 5) GÜVENLİ EŞLEŞME İÇİN ENGEL KELİMELER
# =========================================================

# "ortalama" içinde "orta" geçtiği için Orta Mahallesi yanlış algılanmasın.
LOCATION_FALSE_POSITIVE_GUARDS = [
    "ortalama",
    "ortalamasi",
    "ortalaması",
    "orta fiyat",
    "orta seviye",
    "orta segment",
    "ortaya",
    "ortadan",
    "ortasında",
    "ortasinda",
]


# =========================================================
# 6) ODA TİPİ ALTERNATİF YAZIMLARI
# =========================================================

ROOM_SYNONYMS = {
    "1+0": ["1+0", "stüdyo", "studio", "1 oda"],
    "1+1": ["1+1", "bir arti bir", "bir artı bir"],
    "2+1": ["2+1", "iki arti bir", "iki artı bir"],
    "3+1": ["3+1", "üç artı bir", "uc arti bir", "3 oda 1 salon"],
    "4+1": ["4+1", "dört artı bir", "dort arti bir"],
    "5+1": ["5+1", "beş artı bir", "bes arti bir"],
}


# =========================================================
# 7) GELİŞTİRME NOTLARI
# =========================================================

ROADMAP = [
    "Mahalle trend skorlaması",
    "Aylık fiyat hareketi",
    "Haber/RSS entegrasyonu",
    "Fiyat anomalisi tespiti",
    "Satıcı odaklı fiyat tavsiyesi",
    "Alıcı değil sadece satıcı akışına yönlendirme",
    "İlan açıklaması üretimi",
    "Mahalle güven skoru",
    "Benzer ilanların haritada katmanlı gösterimi",
    "Daha doğal dil anlama",
]

# Aşağıdaki rehber listeleri dosyanın uzun vadede geliştirilebilirliğini artırır.
# Bunlar response builder tarafında kullanılabilir.

SELLER_EDUCATION_TIPS = [
    "Fiyatı çok yüksek açmak ilk haftalarda görüntülenme alabilir ama teklif oranını düşürebilir.",
    "Dengeli fiyat, hızlı satış ile yüksek kazanç arasında en sağlıklı orta noktadır.",
    "Aynı mahalledeki aynı oda tipleri en güçlü emsal grubudur.",
    "Net m² bilgisi brüt m² bilgisinden fiyat tahmini için daha belirleyicidir.",
    "Tapu ve kredi uygunluğu satış sürecini doğrudan etkileyebilir.",
    "Fotoğraf kalitesi fiyat kadar önemli bir ilan performansı faktörüdür.",
    "İlan başlığında ilçe, mahalle, net m² ve oda tipi bulunmalıdır.",
    "İlk 2 hafta ilan performansı takip edilmelidir.",
    "Favori ve mesaj sayısı düşükse fiyat veya açıklama revize edilmelidir.",
    "Pazarlık payı bırakılacaksa ilan fiyatı kapanış hedefinden biraz yukarıda olmalıdır.",
]

MARKET_ANALYSIS_DIMENSIONS = [
    "ortalama_fiyat",
    "medyan_fiyat",
    "minimum_fiyat",
    "maksimum_fiyat",
    "ortalama_m2_fiyati",
    "medyan_m2_fiyati",
    "ilan_sayisi",
    "oda_tipi_dagilimi",
    "mahalle_eslesme_guveni",
    "fiyat_araligi_genisligi",
    "uc_deger_riski",
    "emsal_yakinligi",
    "metrekare_benzerligi",
    "konum_benzerligi",
    "oda_salon_benzerligi",
]

RESPONSE_TONE_RULES = [
    "Cevaplar satıcıya yardımcı olacak şekilde net olmalı.",
    "Veri yoksa tahmin uydurulmamalı.",
    "Seçili mahalle varsa tüm ilçeye izinsiz genişletme yapılmamalı.",
    "Kullanıcı kısa yazsa bile bağlamdan anlam çıkarılmalı.",
    "Fiyatlar TL formatında okunabilir gösterilmeli.",
    "Harita aksiyonu varsa action alanı dönülmeli.",
    "Cevap HTML içinde <br> ve <strong> ile okunabilir olmalı.",
    "Kullanıcıya teknik hata gösterilmemeli; sade yönlendirme yapılmalı.",
    "Ortalama ve medyan birlikte açıklanmalı.",
    "m² fiyatının önemi kısa şekilde belirtilmeli.",
]

# =========================================================
# 8) FAZLA AMA ANLAMLI TEMPLATE BANKASI
# =========================================================

MICRO_RESPONSES = {
    "context_saved": [
        "Bu bölgeyi konuşma bağlamına aldım.",
        "Artık bu mahalle üzerinden devam edebilirim.",
        "Sonraki sorularında ilçe/mahalle yazmana gerek yok.",
    ],
    "context_missing": [
        "Hangi bölgeyi sorduğunu anlayamadım.",
        "Önce bir ilçe ve mahalle belirtmen gerekiyor.",
        "Haritadan konum seçersen onu hatırlayabilirim.",
    ],
    "data_low": [
        "Bu bölgede veri sayısı düşük olduğu için sonuç dikkatli yorumlanmalı.",
        "Benzer ilan sayısı az; analiz güveni sınırlı.",
        "Daha fazla ilan verisiyle daha güçlü sonuç alınır.",
    ],
    "data_good": [
        "Benzer ilan sayısı yeterli görünüyor.",
        "Bu analiz için kullanılabilir seviyede veri var.",
        "Emsal ilanlar fiyat aralığını anlamak için yeterli.",
    ],
}

# Bu dosya zamanla daha da büyütülebilir.
# Ama ana mantık houseai_map_chatbot_service.py içinde çalışır.


EXTENDED_TEMPLATE_BANK = {
    "template_1": "HouseAI emlak analiz şablonu 1: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_2": "HouseAI emlak analiz şablonu 2: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_3": "HouseAI emlak analiz şablonu 3: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_4": "HouseAI emlak analiz şablonu 4: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_5": "HouseAI emlak analiz şablonu 5: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_6": "HouseAI emlak analiz şablonu 6: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_7": "HouseAI emlak analiz şablonu 7: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_8": "HouseAI emlak analiz şablonu 8: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_9": "HouseAI emlak analiz şablonu 9: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_10": "HouseAI emlak analiz şablonu 10: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_11": "HouseAI emlak analiz şablonu 11: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_12": "HouseAI emlak analiz şablonu 12: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_13": "HouseAI emlak analiz şablonu 13: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_14": "HouseAI emlak analiz şablonu 14: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_15": "HouseAI emlak analiz şablonu 15: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_16": "HouseAI emlak analiz şablonu 16: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_17": "HouseAI emlak analiz şablonu 17: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_18": "HouseAI emlak analiz şablonu 18: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_19": "HouseAI emlak analiz şablonu 19: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_20": "HouseAI emlak analiz şablonu 20: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_21": "HouseAI emlak analiz şablonu 21: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_22": "HouseAI emlak analiz şablonu 22: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_23": "HouseAI emlak analiz şablonu 23: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_24": "HouseAI emlak analiz şablonu 24: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_25": "HouseAI emlak analiz şablonu 25: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_26": "HouseAI emlak analiz şablonu 26: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_27": "HouseAI emlak analiz şablonu 27: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_28": "HouseAI emlak analiz şablonu 28: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_29": "HouseAI emlak analiz şablonu 29: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_30": "HouseAI emlak analiz şablonu 30: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_31": "HouseAI emlak analiz şablonu 31: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_32": "HouseAI emlak analiz şablonu 32: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_33": "HouseAI emlak analiz şablonu 33: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_34": "HouseAI emlak analiz şablonu 34: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_35": "HouseAI emlak analiz şablonu 35: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_36": "HouseAI emlak analiz şablonu 36: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_37": "HouseAI emlak analiz şablonu 37: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_38": "HouseAI emlak analiz şablonu 38: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_39": "HouseAI emlak analiz şablonu 39: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_40": "HouseAI emlak analiz şablonu 40: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_41": "HouseAI emlak analiz şablonu 41: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_42": "HouseAI emlak analiz şablonu 42: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_43": "HouseAI emlak analiz şablonu 43: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_44": "HouseAI emlak analiz şablonu 44: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_45": "HouseAI emlak analiz şablonu 45: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_46": "HouseAI emlak analiz şablonu 46: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_47": "HouseAI emlak analiz şablonu 47: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_48": "HouseAI emlak analiz şablonu 48: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_49": "HouseAI emlak analiz şablonu 49: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_50": "HouseAI emlak analiz şablonu 50: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_51": "HouseAI emlak analiz şablonu 51: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_52": "HouseAI emlak analiz şablonu 52: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_53": "HouseAI emlak analiz şablonu 53: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_54": "HouseAI emlak analiz şablonu 54: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_55": "HouseAI emlak analiz şablonu 55: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_56": "HouseAI emlak analiz şablonu 56: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_57": "HouseAI emlak analiz şablonu 57: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_58": "HouseAI emlak analiz şablonu 58: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_59": "HouseAI emlak analiz şablonu 59: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_60": "HouseAI emlak analiz şablonu 60: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_61": "HouseAI emlak analiz şablonu 61: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_62": "HouseAI emlak analiz şablonu 62: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_63": "HouseAI emlak analiz şablonu 63: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_64": "HouseAI emlak analiz şablonu 64: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_65": "HouseAI emlak analiz şablonu 65: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_66": "HouseAI emlak analiz şablonu 66: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_67": "HouseAI emlak analiz şablonu 67: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_68": "HouseAI emlak analiz şablonu 68: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_69": "HouseAI emlak analiz şablonu 69: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_70": "HouseAI emlak analiz şablonu 70: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_71": "HouseAI emlak analiz şablonu 71: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_72": "HouseAI emlak analiz şablonu 72: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_73": "HouseAI emlak analiz şablonu 73: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_74": "HouseAI emlak analiz şablonu 74: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_75": "HouseAI emlak analiz şablonu 75: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_76": "HouseAI emlak analiz şablonu 76: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_77": "HouseAI emlak analiz şablonu 77: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_78": "HouseAI emlak analiz şablonu 78: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_79": "HouseAI emlak analiz şablonu 79: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_80": "HouseAI emlak analiz şablonu 80: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_81": "HouseAI emlak analiz şablonu 81: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_82": "HouseAI emlak analiz şablonu 82: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_83": "HouseAI emlak analiz şablonu 83: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_84": "HouseAI emlak analiz şablonu 84: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_85": "HouseAI emlak analiz şablonu 85: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_86": "HouseAI emlak analiz şablonu 86: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_87": "HouseAI emlak analiz şablonu 87: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_88": "HouseAI emlak analiz şablonu 88: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_89": "HouseAI emlak analiz şablonu 89: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_90": "HouseAI emlak analiz şablonu 90: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_91": "HouseAI emlak analiz şablonu 91: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_92": "HouseAI emlak analiz şablonu 92: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_93": "HouseAI emlak analiz şablonu 93: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_94": "HouseAI emlak analiz şablonu 94: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_95": "HouseAI emlak analiz şablonu 95: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_96": "HouseAI emlak analiz şablonu 96: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_97": "HouseAI emlak analiz şablonu 97: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_98": "HouseAI emlak analiz şablonu 98: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_99": "HouseAI emlak analiz şablonu 99: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_100": "HouseAI emlak analiz şablonu 100: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_101": "HouseAI emlak analiz şablonu 101: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_102": "HouseAI emlak analiz şablonu 102: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_103": "HouseAI emlak analiz şablonu 103: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_104": "HouseAI emlak analiz şablonu 104: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_105": "HouseAI emlak analiz şablonu 105: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_106": "HouseAI emlak analiz şablonu 106: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_107": "HouseAI emlak analiz şablonu 107: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_108": "HouseAI emlak analiz şablonu 108: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_109": "HouseAI emlak analiz şablonu 109: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_110": "HouseAI emlak analiz şablonu 110: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_111": "HouseAI emlak analiz şablonu 111: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_112": "HouseAI emlak analiz şablonu 112: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_113": "HouseAI emlak analiz şablonu 113: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_114": "HouseAI emlak analiz şablonu 114: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_115": "HouseAI emlak analiz şablonu 115: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_116": "HouseAI emlak analiz şablonu 116: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_117": "HouseAI emlak analiz şablonu 117: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_118": "HouseAI emlak analiz şablonu 118: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_119": "HouseAI emlak analiz şablonu 119: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_120": "HouseAI emlak analiz şablonu 120: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_121": "HouseAI emlak analiz şablonu 121: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_122": "HouseAI emlak analiz şablonu 122: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_123": "HouseAI emlak analiz şablonu 123: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_124": "HouseAI emlak analiz şablonu 124: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_125": "HouseAI emlak analiz şablonu 125: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_126": "HouseAI emlak analiz şablonu 126: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_127": "HouseAI emlak analiz şablonu 127: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_128": "HouseAI emlak analiz şablonu 128: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_129": "HouseAI emlak analiz şablonu 129: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_130": "HouseAI emlak analiz şablonu 130: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_131": "HouseAI emlak analiz şablonu 131: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_132": "HouseAI emlak analiz şablonu 132: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_133": "HouseAI emlak analiz şablonu 133: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_134": "HouseAI emlak analiz şablonu 134: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_135": "HouseAI emlak analiz şablonu 135: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_136": "HouseAI emlak analiz şablonu 136: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_137": "HouseAI emlak analiz şablonu 137: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_138": "HouseAI emlak analiz şablonu 138: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_139": "HouseAI emlak analiz şablonu 139: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_140": "HouseAI emlak analiz şablonu 140: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_141": "HouseAI emlak analiz şablonu 141: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_142": "HouseAI emlak analiz şablonu 142: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_143": "HouseAI emlak analiz şablonu 143: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_144": "HouseAI emlak analiz şablonu 144: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_145": "HouseAI emlak analiz şablonu 145: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_146": "HouseAI emlak analiz şablonu 146: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_147": "HouseAI emlak analiz şablonu 147: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_148": "HouseAI emlak analiz şablonu 148: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_149": "HouseAI emlak analiz şablonu 149: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_150": "HouseAI emlak analiz şablonu 150: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_151": "HouseAI emlak analiz şablonu 151: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_152": "HouseAI emlak analiz şablonu 152: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_153": "HouseAI emlak analiz şablonu 153: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_154": "HouseAI emlak analiz şablonu 154: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_155": "HouseAI emlak analiz şablonu 155: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_156": "HouseAI emlak analiz şablonu 156: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_157": "HouseAI emlak analiz şablonu 157: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_158": "HouseAI emlak analiz şablonu 158: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_159": "HouseAI emlak analiz şablonu 159: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_160": "HouseAI emlak analiz şablonu 160: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_161": "HouseAI emlak analiz şablonu 161: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_162": "HouseAI emlak analiz şablonu 162: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_163": "HouseAI emlak analiz şablonu 163: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_164": "HouseAI emlak analiz şablonu 164: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_165": "HouseAI emlak analiz şablonu 165: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_166": "HouseAI emlak analiz şablonu 166: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_167": "HouseAI emlak analiz şablonu 167: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_168": "HouseAI emlak analiz şablonu 168: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_169": "HouseAI emlak analiz şablonu 169: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_170": "HouseAI emlak analiz şablonu 170: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_171": "HouseAI emlak analiz şablonu 171: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_172": "HouseAI emlak analiz şablonu 172: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_173": "HouseAI emlak analiz şablonu 173: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_174": "HouseAI emlak analiz şablonu 174: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_175": "HouseAI emlak analiz şablonu 175: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_176": "HouseAI emlak analiz şablonu 176: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_177": "HouseAI emlak analiz şablonu 177: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_178": "HouseAI emlak analiz şablonu 178: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_179": "HouseAI emlak analiz şablonu 179: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_180": "HouseAI emlak analiz şablonu 180: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_181": "HouseAI emlak analiz şablonu 181: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_182": "HouseAI emlak analiz şablonu 182: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_183": "HouseAI emlak analiz şablonu 183: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_184": "HouseAI emlak analiz şablonu 184: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_185": "HouseAI emlak analiz şablonu 185: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_186": "HouseAI emlak analiz şablonu 186: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_187": "HouseAI emlak analiz şablonu 187: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_188": "HouseAI emlak analiz şablonu 188: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_189": "HouseAI emlak analiz şablonu 189: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_190": "HouseAI emlak analiz şablonu 190: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_191": "HouseAI emlak analiz şablonu 191: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_192": "HouseAI emlak analiz şablonu 192: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_193": "HouseAI emlak analiz şablonu 193: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_194": "HouseAI emlak analiz şablonu 194: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_195": "HouseAI emlak analiz şablonu 195: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_196": "HouseAI emlak analiz şablonu 196: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_197": "HouseAI emlak analiz şablonu 197: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_198": "HouseAI emlak analiz şablonu 198: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_199": "HouseAI emlak analiz şablonu 199: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_200": "HouseAI emlak analiz şablonu 200: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_201": "HouseAI emlak analiz şablonu 201: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_202": "HouseAI emlak analiz şablonu 202: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_203": "HouseAI emlak analiz şablonu 203: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_204": "HouseAI emlak analiz şablonu 204: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_205": "HouseAI emlak analiz şablonu 205: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_206": "HouseAI emlak analiz şablonu 206: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_207": "HouseAI emlak analiz şablonu 207: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_208": "HouseAI emlak analiz şablonu 208: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_209": "HouseAI emlak analiz şablonu 209: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_210": "HouseAI emlak analiz şablonu 210: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_211": "HouseAI emlak analiz şablonu 211: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_212": "HouseAI emlak analiz şablonu 212: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_213": "HouseAI emlak analiz şablonu 213: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_214": "HouseAI emlak analiz şablonu 214: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_215": "HouseAI emlak analiz şablonu 215: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_216": "HouseAI emlak analiz şablonu 216: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_217": "HouseAI emlak analiz şablonu 217: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_218": "HouseAI emlak analiz şablonu 218: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_219": "HouseAI emlak analiz şablonu 219: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_220": "HouseAI emlak analiz şablonu 220: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_221": "HouseAI emlak analiz şablonu 221: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_222": "HouseAI emlak analiz şablonu 222: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_223": "HouseAI emlak analiz şablonu 223: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_224": "HouseAI emlak analiz şablonu 224: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_225": "HouseAI emlak analiz şablonu 225: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_226": "HouseAI emlak analiz şablonu 226: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_227": "HouseAI emlak analiz şablonu 227: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_228": "HouseAI emlak analiz şablonu 228: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_229": "HouseAI emlak analiz şablonu 229: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_230": "HouseAI emlak analiz şablonu 230: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_231": "HouseAI emlak analiz şablonu 231: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_232": "HouseAI emlak analiz şablonu 232: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_233": "HouseAI emlak analiz şablonu 233: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_234": "HouseAI emlak analiz şablonu 234: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_235": "HouseAI emlak analiz şablonu 235: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_236": "HouseAI emlak analiz şablonu 236: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_237": "HouseAI emlak analiz şablonu 237: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_238": "HouseAI emlak analiz şablonu 238: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_239": "HouseAI emlak analiz şablonu 239: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_240": "HouseAI emlak analiz şablonu 240: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_241": "HouseAI emlak analiz şablonu 241: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_242": "HouseAI emlak analiz şablonu 242: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_243": "HouseAI emlak analiz şablonu 243: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_244": "HouseAI emlak analiz şablonu 244: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_245": "HouseAI emlak analiz şablonu 245: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_246": "HouseAI emlak analiz şablonu 246: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_247": "HouseAI emlak analiz şablonu 247: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_248": "HouseAI emlak analiz şablonu 248: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_249": "HouseAI emlak analiz şablonu 249: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_250": "HouseAI emlak analiz şablonu 250: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_251": "HouseAI emlak analiz şablonu 251: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_252": "HouseAI emlak analiz şablonu 252: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_253": "HouseAI emlak analiz şablonu 253: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_254": "HouseAI emlak analiz şablonu 254: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_255": "HouseAI emlak analiz şablonu 255: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_256": "HouseAI emlak analiz şablonu 256: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_257": "HouseAI emlak analiz şablonu 257: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_258": "HouseAI emlak analiz şablonu 258: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_259": "HouseAI emlak analiz şablonu 259: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_260": "HouseAI emlak analiz şablonu 260: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_261": "HouseAI emlak analiz şablonu 261: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_262": "HouseAI emlak analiz şablonu 262: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_263": "HouseAI emlak analiz şablonu 263: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_264": "HouseAI emlak analiz şablonu 264: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_265": "HouseAI emlak analiz şablonu 265: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_266": "HouseAI emlak analiz şablonu 266: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_267": "HouseAI emlak analiz şablonu 267: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_268": "HouseAI emlak analiz şablonu 268: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_269": "HouseAI emlak analiz şablonu 269: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_270": "HouseAI emlak analiz şablonu 270: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_271": "HouseAI emlak analiz şablonu 271: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_272": "HouseAI emlak analiz şablonu 272: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_273": "HouseAI emlak analiz şablonu 273: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_274": "HouseAI emlak analiz şablonu 274: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_275": "HouseAI emlak analiz şablonu 275: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_276": "HouseAI emlak analiz şablonu 276: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_277": "HouseAI emlak analiz şablonu 277: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_278": "HouseAI emlak analiz şablonu 278: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_279": "HouseAI emlak analiz şablonu 279: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_280": "HouseAI emlak analiz şablonu 280: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_281": "HouseAI emlak analiz şablonu 281: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_282": "HouseAI emlak analiz şablonu 282: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_283": "HouseAI emlak analiz şablonu 283: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_284": "HouseAI emlak analiz şablonu 284: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_285": "HouseAI emlak analiz şablonu 285: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_286": "HouseAI emlak analiz şablonu 286: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_287": "HouseAI emlak analiz şablonu 287: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_288": "HouseAI emlak analiz şablonu 288: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_289": "HouseAI emlak analiz şablonu 289: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_290": "HouseAI emlak analiz şablonu 290: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_291": "HouseAI emlak analiz şablonu 291: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_292": "HouseAI emlak analiz şablonu 292: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_293": "HouseAI emlak analiz şablonu 293: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_294": "HouseAI emlak analiz şablonu 294: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_295": "HouseAI emlak analiz şablonu 295: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_296": "HouseAI emlak analiz şablonu 296: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_297": "HouseAI emlak analiz şablonu 297: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_298": "HouseAI emlak analiz şablonu 298: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_299": "HouseAI emlak analiz şablonu 299: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_300": "HouseAI emlak analiz şablonu 300: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_301": "HouseAI emlak analiz şablonu 301: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_302": "HouseAI emlak analiz şablonu 302: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_303": "HouseAI emlak analiz şablonu 303: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_304": "HouseAI emlak analiz şablonu 304: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_305": "HouseAI emlak analiz şablonu 305: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_306": "HouseAI emlak analiz şablonu 306: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_307": "HouseAI emlak analiz şablonu 307: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_308": "HouseAI emlak analiz şablonu 308: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_309": "HouseAI emlak analiz şablonu 309: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_310": "HouseAI emlak analiz şablonu 310: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_311": "HouseAI emlak analiz şablonu 311: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_312": "HouseAI emlak analiz şablonu 312: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_313": "HouseAI emlak analiz şablonu 313: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_314": "HouseAI emlak analiz şablonu 314: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_315": "HouseAI emlak analiz şablonu 315: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_316": "HouseAI emlak analiz şablonu 316: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_317": "HouseAI emlak analiz şablonu 317: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_318": "HouseAI emlak analiz şablonu 318: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_319": "HouseAI emlak analiz şablonu 319: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_320": "HouseAI emlak analiz şablonu 320: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_321": "HouseAI emlak analiz şablonu 321: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_322": "HouseAI emlak analiz şablonu 322: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_323": "HouseAI emlak analiz şablonu 323: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_324": "HouseAI emlak analiz şablonu 324: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_325": "HouseAI emlak analiz şablonu 325: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_326": "HouseAI emlak analiz şablonu 326: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_327": "HouseAI emlak analiz şablonu 327: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_328": "HouseAI emlak analiz şablonu 328: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_329": "HouseAI emlak analiz şablonu 329: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_330": "HouseAI emlak analiz şablonu 330: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_331": "HouseAI emlak analiz şablonu 331: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_332": "HouseAI emlak analiz şablonu 332: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_333": "HouseAI emlak analiz şablonu 333: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_334": "HouseAI emlak analiz şablonu 334: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_335": "HouseAI emlak analiz şablonu 335: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_336": "HouseAI emlak analiz şablonu 336: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_337": "HouseAI emlak analiz şablonu 337: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_338": "HouseAI emlak analiz şablonu 338: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_339": "HouseAI emlak analiz şablonu 339: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_340": "HouseAI emlak analiz şablonu 340: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_341": "HouseAI emlak analiz şablonu 341: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_342": "HouseAI emlak analiz şablonu 342: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_343": "HouseAI emlak analiz şablonu 343: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_344": "HouseAI emlak analiz şablonu 344: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_345": "HouseAI emlak analiz şablonu 345: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_346": "HouseAI emlak analiz şablonu 346: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_347": "HouseAI emlak analiz şablonu 347: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_348": "HouseAI emlak analiz şablonu 348: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_349": "HouseAI emlak analiz şablonu 349: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_350": "HouseAI emlak analiz şablonu 350: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_351": "HouseAI emlak analiz şablonu 351: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_352": "HouseAI emlak analiz şablonu 352: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_353": "HouseAI emlak analiz şablonu 353: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_354": "HouseAI emlak analiz şablonu 354: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_355": "HouseAI emlak analiz şablonu 355: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_356": "HouseAI emlak analiz şablonu 356: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_357": "HouseAI emlak analiz şablonu 357: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_358": "HouseAI emlak analiz şablonu 358: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_359": "HouseAI emlak analiz şablonu 359: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_360": "HouseAI emlak analiz şablonu 360: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_361": "HouseAI emlak analiz şablonu 361: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_362": "HouseAI emlak analiz şablonu 362: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_363": "HouseAI emlak analiz şablonu 363: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_364": "HouseAI emlak analiz şablonu 364: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_365": "HouseAI emlak analiz şablonu 365: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_366": "HouseAI emlak analiz şablonu 366: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_367": "HouseAI emlak analiz şablonu 367: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_368": "HouseAI emlak analiz şablonu 368: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_369": "HouseAI emlak analiz şablonu 369: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_370": "HouseAI emlak analiz şablonu 370: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_371": "HouseAI emlak analiz şablonu 371: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_372": "HouseAI emlak analiz şablonu 372: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_373": "HouseAI emlak analiz şablonu 373: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_374": "HouseAI emlak analiz şablonu 374: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_375": "HouseAI emlak analiz şablonu 375: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_376": "HouseAI emlak analiz şablonu 376: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_377": "HouseAI emlak analiz şablonu 377: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_378": "HouseAI emlak analiz şablonu 378: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_379": "HouseAI emlak analiz şablonu 379: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_380": "HouseAI emlak analiz şablonu 380: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_381": "HouseAI emlak analiz şablonu 381: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_382": "HouseAI emlak analiz şablonu 382: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_383": "HouseAI emlak analiz şablonu 383: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_384": "HouseAI emlak analiz şablonu 384: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_385": "HouseAI emlak analiz şablonu 385: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_386": "HouseAI emlak analiz şablonu 386: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_387": "HouseAI emlak analiz şablonu 387: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_388": "HouseAI emlak analiz şablonu 388: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_389": "HouseAI emlak analiz şablonu 389: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_390": "HouseAI emlak analiz şablonu 390: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_391": "HouseAI emlak analiz şablonu 391: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_392": "HouseAI emlak analiz şablonu 392: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_393": "HouseAI emlak analiz şablonu 393: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_394": "HouseAI emlak analiz şablonu 394: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_395": "HouseAI emlak analiz şablonu 395: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_396": "HouseAI emlak analiz şablonu 396: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_397": "HouseAI emlak analiz şablonu 397: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_398": "HouseAI emlak analiz şablonu 398: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_399": "HouseAI emlak analiz şablonu 399: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_400": "HouseAI emlak analiz şablonu 400: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_401": "HouseAI emlak analiz şablonu 401: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_402": "HouseAI emlak analiz şablonu 402: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_403": "HouseAI emlak analiz şablonu 403: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_404": "HouseAI emlak analiz şablonu 404: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_405": "HouseAI emlak analiz şablonu 405: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_406": "HouseAI emlak analiz şablonu 406: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_407": "HouseAI emlak analiz şablonu 407: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_408": "HouseAI emlak analiz şablonu 408: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_409": "HouseAI emlak analiz şablonu 409: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_410": "HouseAI emlak analiz şablonu 410: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_411": "HouseAI emlak analiz şablonu 411: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_412": "HouseAI emlak analiz şablonu 412: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_413": "HouseAI emlak analiz şablonu 413: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_414": "HouseAI emlak analiz şablonu 414: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_415": "HouseAI emlak analiz şablonu 415: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_416": "HouseAI emlak analiz şablonu 416: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_417": "HouseAI emlak analiz şablonu 417: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_418": "HouseAI emlak analiz şablonu 418: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_419": "HouseAI emlak analiz şablonu 419: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_420": "HouseAI emlak analiz şablonu 420: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_421": "HouseAI emlak analiz şablonu 421: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_422": "HouseAI emlak analiz şablonu 422: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_423": "HouseAI emlak analiz şablonu 423: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_424": "HouseAI emlak analiz şablonu 424: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_425": "HouseAI emlak analiz şablonu 425: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_426": "HouseAI emlak analiz şablonu 426: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_427": "HouseAI emlak analiz şablonu 427: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_428": "HouseAI emlak analiz şablonu 428: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_429": "HouseAI emlak analiz şablonu 429: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_430": "HouseAI emlak analiz şablonu 430: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_431": "HouseAI emlak analiz şablonu 431: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_432": "HouseAI emlak analiz şablonu 432: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_433": "HouseAI emlak analiz şablonu 433: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_434": "HouseAI emlak analiz şablonu 434: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_435": "HouseAI emlak analiz şablonu 435: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_436": "HouseAI emlak analiz şablonu 436: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_437": "HouseAI emlak analiz şablonu 437: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_438": "HouseAI emlak analiz şablonu 438: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_439": "HouseAI emlak analiz şablonu 439: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_440": "HouseAI emlak analiz şablonu 440: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_441": "HouseAI emlak analiz şablonu 441: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_442": "HouseAI emlak analiz şablonu 442: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_443": "HouseAI emlak analiz şablonu 443: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_444": "HouseAI emlak analiz şablonu 444: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_445": "HouseAI emlak analiz şablonu 445: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_446": "HouseAI emlak analiz şablonu 446: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_447": "HouseAI emlak analiz şablonu 447: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_448": "HouseAI emlak analiz şablonu 448: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_449": "HouseAI emlak analiz şablonu 449: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_450": "HouseAI emlak analiz şablonu 450: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_451": "HouseAI emlak analiz şablonu 451: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_452": "HouseAI emlak analiz şablonu 452: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_453": "HouseAI emlak analiz şablonu 453: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_454": "HouseAI emlak analiz şablonu 454: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_455": "HouseAI emlak analiz şablonu 455: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_456": "HouseAI emlak analiz şablonu 456: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_457": "HouseAI emlak analiz şablonu 457: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_458": "HouseAI emlak analiz şablonu 458: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_459": "HouseAI emlak analiz şablonu 459: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_460": "HouseAI emlak analiz şablonu 460: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_461": "HouseAI emlak analiz şablonu 461: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_462": "HouseAI emlak analiz şablonu 462: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_463": "HouseAI emlak analiz şablonu 463: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_464": "HouseAI emlak analiz şablonu 464: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_465": "HouseAI emlak analiz şablonu 465: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_466": "HouseAI emlak analiz şablonu 466: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_467": "HouseAI emlak analiz şablonu 467: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_468": "HouseAI emlak analiz şablonu 468: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_469": "HouseAI emlak analiz şablonu 469: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_470": "HouseAI emlak analiz şablonu 470: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_471": "HouseAI emlak analiz şablonu 471: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_472": "HouseAI emlak analiz şablonu 472: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_473": "HouseAI emlak analiz şablonu 473: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_474": "HouseAI emlak analiz şablonu 474: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_475": "HouseAI emlak analiz şablonu 475: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_476": "HouseAI emlak analiz şablonu 476: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_477": "HouseAI emlak analiz şablonu 477: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_478": "HouseAI emlak analiz şablonu 478: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_479": "HouseAI emlak analiz şablonu 479: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_480": "HouseAI emlak analiz şablonu 480: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_481": "HouseAI emlak analiz şablonu 481: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_482": "HouseAI emlak analiz şablonu 482: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_483": "HouseAI emlak analiz şablonu 483: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_484": "HouseAI emlak analiz şablonu 484: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_485": "HouseAI emlak analiz şablonu 485: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_486": "HouseAI emlak analiz şablonu 486: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_487": "HouseAI emlak analiz şablonu 487: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_488": "HouseAI emlak analiz şablonu 488: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_489": "HouseAI emlak analiz şablonu 489: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_490": "HouseAI emlak analiz şablonu 490: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_491": "HouseAI emlak analiz şablonu 491: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_492": "HouseAI emlak analiz şablonu 492: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_493": "HouseAI emlak analiz şablonu 493: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_494": "HouseAI emlak analiz şablonu 494: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_495": "HouseAI emlak analiz şablonu 495: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_496": "HouseAI emlak analiz şablonu 496: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_497": "HouseAI emlak analiz şablonu 497: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_498": "HouseAI emlak analiz şablonu 498: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_499": "HouseAI emlak analiz şablonu 499: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_500": "HouseAI emlak analiz şablonu 500: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_501": "HouseAI emlak analiz şablonu 501: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_502": "HouseAI emlak analiz şablonu 502: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_503": "HouseAI emlak analiz şablonu 503: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_504": "HouseAI emlak analiz şablonu 504: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_505": "HouseAI emlak analiz şablonu 505: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_506": "HouseAI emlak analiz şablonu 506: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_507": "HouseAI emlak analiz şablonu 507: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_508": "HouseAI emlak analiz şablonu 508: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_509": "HouseAI emlak analiz şablonu 509: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_510": "HouseAI emlak analiz şablonu 510: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_511": "HouseAI emlak analiz şablonu 511: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_512": "HouseAI emlak analiz şablonu 512: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_513": "HouseAI emlak analiz şablonu 513: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_514": "HouseAI emlak analiz şablonu 514: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_515": "HouseAI emlak analiz şablonu 515: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_516": "HouseAI emlak analiz şablonu 516: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_517": "HouseAI emlak analiz şablonu 517: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_518": "HouseAI emlak analiz şablonu 518: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_519": "HouseAI emlak analiz şablonu 519: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_520": "HouseAI emlak analiz şablonu 520: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_521": "HouseAI emlak analiz şablonu 521: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_522": "HouseAI emlak analiz şablonu 522: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_523": "HouseAI emlak analiz şablonu 523: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_524": "HouseAI emlak analiz şablonu 524: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_525": "HouseAI emlak analiz şablonu 525: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_526": "HouseAI emlak analiz şablonu 526: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_527": "HouseAI emlak analiz şablonu 527: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_528": "HouseAI emlak analiz şablonu 528: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_529": "HouseAI emlak analiz şablonu 529: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_530": "HouseAI emlak analiz şablonu 530: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_531": "HouseAI emlak analiz şablonu 531: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_532": "HouseAI emlak analiz şablonu 532: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_533": "HouseAI emlak analiz şablonu 533: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_534": "HouseAI emlak analiz şablonu 534: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_535": "HouseAI emlak analiz şablonu 535: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_536": "HouseAI emlak analiz şablonu 536: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_537": "HouseAI emlak analiz şablonu 537: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_538": "HouseAI emlak analiz şablonu 538: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_539": "HouseAI emlak analiz şablonu 539: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_540": "HouseAI emlak analiz şablonu 540: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_541": "HouseAI emlak analiz şablonu 541: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_542": "HouseAI emlak analiz şablonu 542: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_543": "HouseAI emlak analiz şablonu 543: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_544": "HouseAI emlak analiz şablonu 544: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_545": "HouseAI emlak analiz şablonu 545: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_546": "HouseAI emlak analiz şablonu 546: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_547": "HouseAI emlak analiz şablonu 547: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_548": "HouseAI emlak analiz şablonu 548: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_549": "HouseAI emlak analiz şablonu 549: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_550": "HouseAI emlak analiz şablonu 550: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_551": "HouseAI emlak analiz şablonu 551: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_552": "HouseAI emlak analiz şablonu 552: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_553": "HouseAI emlak analiz şablonu 553: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_554": "HouseAI emlak analiz şablonu 554: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_555": "HouseAI emlak analiz şablonu 555: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_556": "HouseAI emlak analiz şablonu 556: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_557": "HouseAI emlak analiz şablonu 557: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_558": "HouseAI emlak analiz şablonu 558: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_559": "HouseAI emlak analiz şablonu 559: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_560": "HouseAI emlak analiz şablonu 560: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_561": "HouseAI emlak analiz şablonu 561: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_562": "HouseAI emlak analiz şablonu 562: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_563": "HouseAI emlak analiz şablonu 563: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_564": "HouseAI emlak analiz şablonu 564: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_565": "HouseAI emlak analiz şablonu 565: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_566": "HouseAI emlak analiz şablonu 566: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_567": "HouseAI emlak analiz şablonu 567: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_568": "HouseAI emlak analiz şablonu 568: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_569": "HouseAI emlak analiz şablonu 569: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_570": "HouseAI emlak analiz şablonu 570: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_571": "HouseAI emlak analiz şablonu 571: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_572": "HouseAI emlak analiz şablonu 572: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_573": "HouseAI emlak analiz şablonu 573: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_574": "HouseAI emlak analiz şablonu 574: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_575": "HouseAI emlak analiz şablonu 575: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_576": "HouseAI emlak analiz şablonu 576: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_577": "HouseAI emlak analiz şablonu 577: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_578": "HouseAI emlak analiz şablonu 578: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_579": "HouseAI emlak analiz şablonu 579: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_580": "HouseAI emlak analiz şablonu 580: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_581": "HouseAI emlak analiz şablonu 581: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_582": "HouseAI emlak analiz şablonu 582: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_583": "HouseAI emlak analiz şablonu 583: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_584": "HouseAI emlak analiz şablonu 584: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_585": "HouseAI emlak analiz şablonu 585: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_586": "HouseAI emlak analiz şablonu 586: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_587": "HouseAI emlak analiz şablonu 587: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_588": "HouseAI emlak analiz şablonu 588: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_589": "HouseAI emlak analiz şablonu 589: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_590": "HouseAI emlak analiz şablonu 590: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_591": "HouseAI emlak analiz şablonu 591: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_592": "HouseAI emlak analiz şablonu 592: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_593": "HouseAI emlak analiz şablonu 593: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_594": "HouseAI emlak analiz şablonu 594: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_595": "HouseAI emlak analiz şablonu 595: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_596": "HouseAI emlak analiz şablonu 596: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_597": "HouseAI emlak analiz şablonu 597: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_598": "HouseAI emlak analiz şablonu 598: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_599": "HouseAI emlak analiz şablonu 599: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
    "template_600": "HouseAI emlak analiz şablonu 600: seçili mahalle, oda tipi ve m² fiyatı bağlamını koru.",
}
